[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/zalando/go-keyring"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
